server:
  port: 8088

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: webinar-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:consort-postgres}:${DB_PORT:5432}/${POSTGRES_DB:consort_group}}
    username: ${DB_USERNAME:${POSTGRES_USER:consort}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:}}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_WEBINAR_HOST:consort-redis-webinar-service}
      port: ${REDIS_WEBINAR_PORT:6379}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: INFO
    org.springframework: DEBUG

app:
  preview:
    base-url: /api/v1/webinars/preview/

security:
  token: ${SECURITY_TOKEN}
  expiration: 3600000

storage:
  base-dir: uploads
  image:
    sub-dir: images
    max-file-size: 100MB
    allowed-mime-types:
      - image/jpeg
      - image/png
    allowed-extensions:
      - jpg
      - jpeg
      - png

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://consort-eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${HOSTNAME}:${server.port}

user:
  service:
    url: http://consort-user-service:8081

course:
  service:
    url: http://consort-course-service:8084

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha
  model-converters:
    pageable-converter:
      enabled: true
