server:
  port: 8088

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: webinar-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: consort-redis-webinar-service
      port: 6379

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: INFO
    org.springframework: DEBUG

app:
  preview:
    base-url: /api/v1/webinars/preview/

security:
  token: ${SECURITY_TOKEN}
  expiration: 3600000

storage:
  base-dir: uploads
  image:
    sub-dir: images
    max-file-size: 100MB
    allowed-mime-types:
      - image/jpeg
      - image/png
    allowed-extensions:
      - jpg
      - jpeg
      - png

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8762/eureka/
  instance:
    prefer-ip-address: true

user:
  service:
    url: http://consort-user-service:8081

course:
  service:
    url: http://consort-course-service:8084

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha

  model-converters:
    pageable-converter:
      enabled: true
